logging:
  level:
    com:
      example:
        bankcards: DEBUG
spring:
  jpa:
    hibernate:
      ddl-auto: validate

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
management:
  endpoints:
    access:
      default: unrestricted
    web:
      exposure:
        include: '*'
application:
     liquibase:
      async: false
