services:
  bankapp:
    image: bankcards-app:this
    container_name: bank_app_runner
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/bank
      SPRING_DATASOURCE_USERNAME: bank
      SPRING_DATASOURCE_PASSWORD:
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI: http://keycloak:9081/realms/seed4j
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
      - "8081:8081"               
    depends_on:
      postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/management/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    restart: unless-stopped